# Use the official Python image as a base image
FROM python:3.9-slim

# Set environment variables for Streamlit
ENV STREAMLIT_HOME /root/.streamlit
ENV STREAMLIT_CONFIG_PATH $STREAMLIT_HOME/config.toml
ENV STREAMLIT_SERVER_PORT 8501

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libgl1-mesa-glx && \
    rm -rf /var/lib/apt/lists/*

# Set up Streamlit
RUN mkdir -p $STREAMLIT_HOME && \
    mkdir -p /app

# Copy the requirements file and install dependencies
COPY requirements.txt /app/
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application files
COPY . /app

# Expose the Streamlit port
EXPOSE $STREAMLIT_SERVER_PORT

# Command to run the Streamlit app
CMD ["streamlit", "run", "LuminaStockMain.py"]
